#
# Travis build configuration
#

language: cpp

before-install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - sudo apt-get install -y build-essential 
  - sudo apt-get install -y libwxgtk3.0-dev  
  - sudo apt-get install -y libssl-dev 
  - sudo apt-get install -y libpcap0.8-dev 
  - sudo apt-get install -y libcurl4-openssl-dev 
  - sudo apt-get install -y libpcap-dev 

install:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      pip install --user cpp-coveralls;
    fi


before_script:
# Check some settings of the build server (operating system, IPv6 availability, directory)
  - uname -a
  - ifconfig
  - pwd
  - ls -la
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      apt-cache search gcc | grep "GNU C compiler";
      apt-cache search clang | grep compiler;
    fi
  - if [[ "${BUILD_TYPE}" == "OSX_OPENSSL_1_1" ]]; then brew install openssl@1.1 ;fi
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libwxgtk3.0-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libpcap0.8-dev
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y libpcap-dev

script: ./configure && make && sudo make install

